<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/test/test.proto

namespace Enqueue\Gps\Tests\Test\Metadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�
events/test/test.prototest"
AddTest
description (	B�Z9github.com/urbansportsclub/arena/build/gen/go/events/Test�Usg.Events.Test�USC\\Arena\\Events\\Test�USC\\Arena\\Events\\Test\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

