<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/test/test.proto

namespace Enqueue\Gps\Tests\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>test.AddTest</code>
 */
class AddTest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     * }
     */
    public function __construct($data = NULL) {
        \Enqueue\Gps\Tests\Test\Metadata\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

